AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  stockscraping:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: stock_scraping
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::538848337497:role/service-role/stock_scraping-role-654etqdc'
      Runtime: python3.7
      Timeout: 120
